POST http://localhost:3000/empleado/alta
Content-Type: application/json

{
    "nombre": "Bruno",
    "apellido": "Cerutti",
    "email": "bruno@gmail.com",
    "usuario": "bruno88",
    "password": "123",
    "telefono": "2657",
    "dni": "123456"
}