GET http://localhost:3000/empleado/crear

###
POST http://localhost:3000/empleado/alta
Content-Type: application/json

{
    "nombre": "Bruno",
    "apellido": "Cerutti",
    "email": "bruno88@gmail.com",
    "usuario": "bruno88",
    "password": "123123",
    "telefono": "111333",
    "dni": "0002"
}

###
PATCH http://localhost:3000/empleado/baja/5
Cookie: token= 'aqui va el token'

