POST http://localhost:3000/vehiculo/alta
Content-Type: application/json

{
    "modelo": "Polo",
    "marca": "Volkswagen",
    "anio": 2014,
    "color": "blanco",
    "cantidad": 2,
    "precio": 2000
}

###
PATCH http://localhost:3000/vehiculo/baja/1

###
PATCH http://localhost:3000/vehiculo/activar/1

###
GET  http://localhost:3000/vehiculo/todos

###
GET  http://localhost:3000/vehiculo/info/1

###
PUT http://localhost:3000/vehiculo/editar/1
Content-Type: application/json

{
    "modelo": "Voyage",
    "marca": "Volkswagen",
    "anio": 2014,
    "color": "blanco",
    "cantidad": 5,
    "precio": 2000
}
